version: '3.8'

services:
  conferences_db:
    image: postgres:latest
    container_name: conferences_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    volumes:
      - ./:/home
    networks:
      - conferences_network
  
  conferences_pgadmin:
    image: dpage/pgadmin4
    container_name: conferences_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "8081:80"
    depends_on:
      - conferences_db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - conferences_network

volumes:
  pgadmin_data:

networks:
  conferences_network:
    external: true
